[package]
name = "gitlab-runner-mock"
version = "0.0.2-alpha.1"
authors = ["Sjoerd Simons <sjoerd@collabora.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Mock crate for gitlab runners"
homepage = "https://github.com/collabora/gitlab-runner-rs"
repository = "https://github.com/collabora/gitlab-runner-rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wiremock = "0.5.2"
serde = "1.0.125"
serde_json = "1.0.64"
url = "2.2.1"
thiserror = "1.0.24"
multipart = { version = "0.18.0", features = [] }
http-types = "2.11.1"
